language: cpp

jobs:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libboost-all-dev
    - os: osx
      addons:
        homebrew:
          packages:
            - boost
          
script: mkdir build && cd build && cmake .. && cmake --build . && ctest

